### ISSUE TITLE
Crash when open setting

### ISSUE THREAD

**Issue by muhammadarif1** [jmalenko/DrawingForKids#1]
#### EXPECTED BEHAVIOR
users should be able to access the settings section to view saved images
#### ACTUAL BEHAVIOR
when the user accesses the settings section, the application crashes
#### STEP TO REPRODUCE
- download and install the app
- open the app, scroll up to the notification section.
- click setting and wait for few second and see error

#### device : oppo neo 7
os: android 6.0
app version: drawing for kids v 6.0

#### BUG RECORDING
https://youtu.be/b1oBHHO9rWo
log cat
```FATAL EXCEPTION: main
Process: cz.jaro.drawing, PID: 20749
d.e: lateinit property skuDetailsMap has not been initialized
	at cz.jaro.drawing.d.c()
	at cz.jaro.drawing.f.a()
	at com.android.billingclient.api.f.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by jmalenko** [comment]
Fixed in release 7.
